#!/bin/bash
# Crypto Scraper API - Quick Command Reference
# Keep this file for easy reference

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║       CRYPTO SCRAPER API - QUICK COMMAND REFERENCE           ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

echo "🚀 DEPLOYMENT"
echo "─────────────────────────────────────────────────────────────────"
echo "  ./deploy.sh                    # Deploy with one command"
echo "  vercel --prod                  # Manual Vercel deployment"
echo "  git push origin main           # Push changes to GitHub"
echo ""

echo "💻 LOCAL DEVELOPMENT"
echo "─────────────────────────────────────────────────────────────────"
echo "  ./setup.sh                     # Setup & run locally"
echo "  source venv/bin/activate       # Activate virtual environment"
echo "  python api.py                  # Run API server"
echo ""

echo "🧪 TESTING"
echo "─────────────────────────────────────────────────────────────────"
echo "  curl http://localhost:3000/api/health       # Health check"
echo "  curl http://localhost:3000/api/results      # Get results"
echo "  curl http://localhost:3000/api/stats        # Get stats"
echo "  curl -X POST http://localhost:3000/api/scrape # Trigger"
echo ""

echo "📚 DOCUMENTATION"
echo "─────────────────────────────────────────────────────────────────"
echo "  QUICKSTART.md        # 5-minute setup guide"
echo "  API_DOCS.md          # Complete API reference"
echo "  DEPLOYMENT.md        # Detailed deployment guide"
echo "  SETUP_SUMMARY.md     # This setup summary"
echo ""

echo "⚙️  CONFIGURATION"
echo "─────────────────────────────────────────────────────────────────"
echo "  .env.local           # Environment variables template"
echo "  vercel.json          # Vercel deployment config"
echo "  config.py            # Scraper configuration"
echo ""

echo "🔗 IMPORTANT LINKS"
echo "─────────────────────────────────────────────────────────────────"
echo "  Vercel Dashboard:    https://vercel.com"
echo "  GitHub Repository:   https://github.com/YOUR_USERNAME/x_scrapper"
echo "  Scheduler Service:   https://cron-job.org"
echo "  API Docs:            https://YOUR_DOMAIN.vercel.app/api"
echo ""

echo "📊 API ENDPOINTS"
echo "─────────────────────────────────────────────────────────────────"
echo "  GET  /api/health              Health check"
echo "  GET  /api/results             Latest 100 tweets"
echo "  GET  /api/results/:account    Account tweets"
echo "  POST /api/scrape              Trigger scraper"
echo "  GET  /api/logs                Scraper logs"
echo "  GET  /api/stats               Database stats"
echo ""

echo "🔑 GITHUB SECRETS (for GitHub Actions)"
echo "─────────────────────────────────────────────────────────────────"
echo "  VERCEL_TOKEN         From: https://vercel.com/account/tokens"
echo "  VERCEL_ORG_ID        From: Vercel project settings"
echo "  VERCEL_PROJECT_ID    From: Vercel project settings"
echo "  SCRAPER_API_URL      Your Vercel domain"
echo ""

echo "✅ DEPLOYMENT CHECKLIST"
echo "─────────────────────────────────────────────────────────────────"
echo "  [ ] Create GitHub repository"
echo "  [ ] Push code to GitHub"
echo "  [ ] Deploy to Vercel"
echo "  [ ] Set environment variables in Vercel"
echo "  [ ] Test API endpoints"
echo "  [ ] Configure external scheduler (cron-job.org)"
echo "  [ ] Enable GitHub Actions (if using)"
echo "  [ ] Monitor logs"
echo ""

echo "🐛 DEBUGGING"
echo "─────────────────────────────────────────────────────────────────"
echo "  vercel logs                    View Vercel logs"
echo "  curl YOUR_DOMAIN/api/logs      View scraper logs"
echo "  curl YOUR_DOMAIN/api/health    Check if online"
echo ""

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║            For detailed help, see QUICKSTART.md               ║"
echo "╚════════════════════════════════════════════════════════════════╝"
