"""
Optional Visualization Module
Generates charts and reports from scraped data
"""

import json
from datetime import datetime, timedelta
from collections import Counter
from pathlib import Path


def generate_text_report(db, hours=24, output_file='text_report.txt'):
    """Generate a human-readable text report"""
    
    since = (datetime.now() - timedelta(hours=hours)).isoformat()
    tweets = db.get_tweets(filters={'since': since}, limit=10000)
    
    if not tweets:
        return "No data available for the specified time period."
    
    # Calculate statistics
    total_tweets = len(tweets)
    total_likes = sum(t['likes'] for t in tweets)
    total_retweets = sum(t['retweets'] for t in tweets)
    total_engagement = total_likes + total_retweets
    
    # Sentiment breakdown
    sentiment_counts = Counter(t.get('sentiment_label', 'neutral') for t in tweets)
    
    # Top accounts
    account_activity = Counter(t['username'] for t in tweets)
    top_accounts = account_activity.most_common(10)
    
    # Top hashtags
    all_hashtags = []
    for tweet in tweets:
        all_hashtags.extend(tweet.get('hashtags', []))
    top_hashtags = Counter(all_hashtags).most_common(20)
    
    # Most engaging tweets
    engaging_tweets = sorted(tweets, key=lambda t: t['likes'] + t['retweets'] * 2, reverse=True)[:10]
    
    # Build report
    report = f"""
╔══════════════════════════════════════════════════════════════╗
║       CRYPTO TWITTER INTELLIGENCE REPORT                     ║
║       Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}                            ║
║       Time Period: Last {hours} hours                              ║
╚══════════════════════════════════════════════════════════════╝

📊 SUMMARY STATISTICS
{'─' * 64}
Total Tweets Analyzed:        {total_tweets:,}
Total Likes:                  {total_likes:,}
Total Retweets:               {total_retweets:,}
Total Engagement:             {total_engagement:,}
Average Engagement/Tweet:     {total_engagement/total_tweets:.1f}
Unique Accounts:              {len(account_activity)}

😊 SENTIMENT ANALYSIS
{'─' * 64}
Positive: {sentiment_counts['positive']:>6} tweets ({sentiment_counts['positive']/total_tweets*100:>5.1f}%)
Neutral:  {sentiment_counts['neutral']:>6} tweets ({sentiment_counts['neutral']/total_tweets*100:>5.1f}%)
Negative: {sentiment_counts['negative']:>6} tweets ({sentiment_counts['negative']/total_tweets*100:>5.1f}%)

👥 TOP 10 MOST ACTIVE ACCOUNTS
{'─' * 64}
"""
    
    for i, (username, count) in enumerate(top_accounts, 1):
        report += f"{i:2}. @{username:<20} {count:>4} tweets\n"
    
    report += f"""
#️⃣  TOP 20 TRENDING HASHTAGS
{'─' * 64}
"""
    
    for i, (hashtag, count) in enumerate(top_hashtags, 1):
        report += f"{i:2}. #{hashtag:<25} {count:>5} mentions\n"
    
    report += f"""
🔥 TOP 10 MOST ENGAGING TWEETS
{'─' * 64}
"""
    
    for i, tweet in enumerate(engaging_tweets, 1):
        engagement = tweet['likes'] + tweet['retweets']
        text = tweet['text'][:100] + ('...' if len(tweet['text']) > 100 else '')
        report += f"\n{i}. @{tweet['username']} ({engagement:,} engagement)\n"
        report += f"   {text}\n"
        report += f"   ❤️  {tweet['likes']:,} | 🔄 {tweet['retweets']:,} | 😊 {tweet.get('sentiment_label', 'N/A')}\n"
    
    report += f"""
{'═' * 64}
Report generated by Crypto Twitter Intelligence System
For more details, see the JSON export or query the database directly
{'═' * 64}
"""
    
    # Save report
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(report)
    
    return report


def generate_csv_export(db, hours=24, output_file='tweets_export.csv'):
    """Export tweets to CSV format"""
    import csv
    
    since = (datetime.now() - timedelta(hours=hours)).isoformat()
    tweets = db.get_tweets(filters={'since': since}, limit=50000)
    
    if not tweets:
        return 0
    
    # Define CSV columns
    columns = [
        'tweet_id', 'username', 'display_name', 'text', 'timestamp',
        'likes', 'retweets', 'replies', 'sentiment_score', 'sentiment_label',
        'hashtags', 'mentions', 'source'
    ]
    
    with open(output_file, 'w', newline='', encoding='utf-8') as f:
        writer = csv.DictWriter(f, fieldnames=columns)
        writer.writeheader()
        
        for tweet in tweets:
            row = {col: tweet.get(col, '') for col in columns}
            # Convert lists to strings
            row['hashtags'] = ', '.join(tweet.get('hashtags', []))
            row['mentions'] = ', '.join(tweet.get('mentions', []))
            writer.writerow(row)
    
    return len(tweets)


def create_html_dashboard(db, hours=24, output_file='dashboard.html'):
    """Create a simple HTML dashboard"""
    
    analysis = db.get_trending_analysis(hours=hours)
    
    html = f"""
<!DOCTYPE html>
<html>
<head>
    <title>Crypto Twitter Intelligence Dashboard</title>
    <meta charset="utf-8">
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Arial, sans-serif;
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            background: #0a0e27;
            color: #e0e0e0;
        }}
        .header {{
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            padding: 30px;
            border-radius: 10px;
            margin-bottom: 30px;
            text-align: center;
        }}
        .header h1 {{
            margin: 0;
            color: white;
            font-size: 2.5em;
        }}
        .stats-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
            gap: 20px;
            margin-bottom: 30px;
        }}
        .stat-card {{
            background: #1a1f3a;
            padding: 20px;
            border-radius: 10px;
            border: 1px solid #2d3561;
        }}
        .stat-value {{
            font-size: 2.5em;
            font-weight: bold;
            color: #667eea;
        }}
        .stat-label {{
            color: #8b92b0;
            margin-top: 5px;
        }}
        .section {{
            background: #1a1f3a;
            padding: 25px;
            border-radius: 10px;
            margin-bottom: 20px;
            border: 1px solid #2d3561;
        }}
        .section h2 {{
            margin-top: 0;
            color: #667eea;
            border-bottom: 2px solid #667eea;
            padding-bottom: 10px;
        }}
        .hashtag-list, .account-list {{
            list-style: none;
            padding: 0;
        }}
        .hashtag-list li, .account-list li {{
            padding: 10px;
            margin: 5px 0;
            background: #0f1729;
            border-radius: 5px;
            display: flex;
            justify-content: space-between;
        }}
        .sentiment-bar {{
            display: flex;
            height: 40px;
            border-radius: 5px;
            overflow: hidden;
            margin: 20px 0;
        }}
        .positive {{ background: #10b981; }}
        .neutral {{ background: #6b7280; }}
        .negative {{ background: #ef4444; }}
        .footer {{
            text-align: center;
            padding: 20px;
            color: #6b7280;
            font-size: 0.9em;
        }}
    </style>
</head>
<body>
    <div class="header">
        <h1>🚀 Crypto Twitter Intelligence</h1>
        <p>Real-time Analysis Dashboard</p>
        <p style="font-size: 0.9em; opacity: 0.8;">Last {hours} hours | Generated {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
    </div>
    
    <div class="stats-grid">
        <div class="stat-card">
            <div class="stat-value">{analysis['total_tweets']:,}</div>
            <div class="stat-label">Total Tweets</div>
        </div>
        <div class="stat-card">
            <div class="stat-value">{len(analysis['top_accounts'])}</div>
            <div class="stat-label">Active Accounts</div>
        </div>
        <div class="stat-card">
            <div class="stat-value">{len(analysis['top_hashtags'])}</div>
            <div class="stat-label">Trending Hashtags</div>
        </div>
    </div>
    
    <div class="section">
        <h2>😊 Sentiment Distribution</h2>
        <div class="sentiment-bar">
"""
    
    # Calculate percentages
    sentiment = analysis['sentiment_breakdown']
    total = sum(sentiment.values())
    if total > 0:
        pos_pct = (sentiment.get('positive', 0) / total) * 100
        neu_pct = (sentiment.get('neutral', 0) / total) * 100
        neg_pct = (sentiment.get('negative', 0) / total) * 100
        
        html += f"""
            <div class="positive" style="width: {pos_pct}%; display: flex; align-items: center; justify-content: center; color: white; font-weight: bold;">
                {sentiment.get('positive', 0)} ({pos_pct:.1f}%)
            </div>
            <div class="neutral" style="width: {neu_pct}%; display: flex; align-items: center; justify-content: center; color: white; font-weight: bold;">
                {sentiment.get('neutral', 0)} ({neu_pct:.1f}%)
            </div>
            <div class="negative" style="width: {neg_pct}%; display: flex; align-items: center; justify-content: center; color: white; font-weight: bold;">
                {sentiment.get('negative', 0)} ({neg_pct:.1f}%)
            </div>
"""
    
    html += """
        </div>
    </div>
    
    <div class="section">
        <h2>#️⃣ Trending Hashtags</h2>
        <ul class="hashtag-list">
"""
    
    for tag_data in analysis['top_hashtags'][:15]:
        html += f"""
            <li>
                <span>#{tag_data['tag']}</span>
                <span><strong>{tag_data['mentions']:,}</strong> mentions | <strong>{tag_data['engagement']:,}</strong> engagement</span>
            </li>
"""
    
    html += """
        </ul>
    </div>
    
    <div class="section">
        <h2>👥 Most Active Accounts</h2>
        <ul class="account-list">
"""
    
    for account in analysis['top_accounts'][:10]:
        html += f"""
            <li>
                <span>@{account['username']}</span>
                <span><strong>{account['tweets']}</strong> tweets | <strong>{account['engagement']:,}</strong> engagement</span>
            </li>
"""
    
    html += """
        </ul>
    </div>
    
    <div class="footer">
        <p>Generated by Crypto Twitter Intelligence System</p>
        <p>For detailed analysis, check the JSON export or query the database</p>
    </div>
</body>
</html>
"""
    
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(html)
    
    return output_file


print("Visualization module loaded")
